DACSWebBanFlower/Controllers/StoreController.cs
using DACSWebBanFlower.Models;
using Microsoft.AspNetCore.Mvc;
using DACSWebBanFlower.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using DACSWebBanFlower.Models.ProductModels;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using DACSWebBanFlower.Repositories;

namespace DACSWebBanFlower.Controllers
{
    public class StoreController : Controller
    {
        private readonly QlbanFlowerContext _context;
        private readonly IDanhMucSpRepository _danhMucSpRepository;
        // Định nghĩa thuộc tính HttpContextAccessor để truy xuất HttpContext
        private readonly IHttpContextAccessor _httpContextAccessor;
        // Constructor để inject IHttpContextAccessor vào controller
        public StoreController(QlbanFlowerContext context,IDanhMucSpRepository danhMucSpRepository , IHttpContextAccessor httpContextAccessor)
        {
            _danhMucSpRepository = danhMucSpRepository;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
        }

        public ShoppingCart Carts
        {
            get
            {
                var session = _httpContextAccessor.HttpContext.Session; // Lấy session từ HttpContextAccessor
                var cart = session.GetObjectFromJson<ShoppingCart>("GioHang"); // Sử dụng Extension Helpers để lấy dữ liệu từ session
                if (cart == null)
                {
                    cart = new ShoppingCart();
                }
                return cart;
            }   
            set
            {
                var session = _httpContextAccessor.HttpContext.Session; // Lấy session từ HttpContextAccessor
                session.SetObjectAsJson("GioHang", value); // Sử dụng Extension Helpers để lưu dữ liệu vào session
            }
        }

        public IActionResult AddToCart(string id, int SoLuong)
        {
            var myCart = Carts;
            var item = myCart.Items.SingleOrDefault(p=>p.MaSp==id);
            if (item == null)
            {
                var sanPham = _context.TDanhMucSps.SingleOrDefault(p => p.Id == id);
                item = new CartItem
                {
                    MaSp = id,
                    TenSp = sanPham.TenSp,
                    Price = sanPham.GiaNhoNhat, // Gán giá trị của thuộc tính Price của đối tượng sanPham vào thuộc tính Price của item
                    SoLuong = 1,
                };
                myCart.Items.Add(item);
            }
            else
            {   
                item.SoLuong++;
            }
            HttpContext.Session.SetObjectAsJson("GioHang", myCart);

            return RedirectToAction("Index");
        }
        //============================================================================
        //Cap nhap lai gio hang
        [HttpPost]
        public IActionResult UpdateCartItem(string id, int SoLuong)
        {
            // Kiểm tra dữ liệu đầu vào
            if (SoLuong <= 0)
            {
                // Xử lý khi số lượng không hợp lệ
                // Ví dụ: Hiển thị thông báo lỗi và redirect về trang giỏ hàng
                TempData["ErrorMessage"] = "Số lượng không hợp lệ.";
                return RedirectToAction("Index");
            }

            var myCart = Carts;
            var item = myCart.Items.SingleOrDefault(p => p.MaSp == id);

            // Kiểm tra sản phẩm có tồn tại không
            if (item == null)
            {
                // Xử lý khi sản phẩm không tồn tại trong giỏ hàng
                // Ví dụ: Hiển thị thông báo lỗi và redirect về trang giỏ hàng
                TempData["ErrorMessage"] = "Sản phẩm không tồn tại trong giỏ hàng.";
                return RedirectToAction("Index");
            }

            // Cập nhật số lượng của sản phẩm
            item.SoLuong = SoLuong;
            Carts = myCart;

            return RedirectToAction("Index");
        }

        // Xóa sản phẩm khỏi giỏ hàng
        [HttpPost]
        public IActionResult RemoveFromCart(string id)
        {
            var myCart = Carts;
            var item = myCart.Items.SingleOrDefault(p => p.MaSp == id);
            if (item != null)
            {
                myCart.Items.Remove(item);
                Carts = myCart;
            }
            return RedirectToAction("Index");
        }

        // Xóa toàn bộ sản phẩm khỏi giỏ hàng
        [HttpPost]
        public IActionResult ClearAll()
        {
            Carts.Items.Clear();
            HttpContext.Session.Remove("GioHang");
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("GioHang") ?? new ShoppingCart();
            return View(cart); // Truyền giỏ hàng vào view
        }


        //================================================================================

        [HttpGet]
        public IActionResult ThanhToan()
        {
            return View(new THoaDonBan());
        }
        
        [HttpPost]
        public async Task<IActionResult> ThanhToan(THoaDonBan hoaDonBan)
        {
            // Kiểm tra xem session có tồn tại hay không
            if (HttpContext.Session.Keys.Contains("GioHang"))
            {
                // Session đã tồn tại
                var gioHang = HttpContext.Session.GetObjectFromJson<ShoppingCart>("GioHang");
                // Tiếp tục xử lý dựa trên giỏ hàng
            }
            else
            {
                // Session chưa tồn tại
                // Thực hiện các hành động phù hợp
            }
            var Carts = HttpContext.Session.GetObjectFromJson<ShoppingCart>("GioHang");
            if (Carts == null || !Carts.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            
            hoaDonBan.NgayHoaDon = DateTime.UtcNow;
            hoaDonBan.TongTienHd = Carts.Items.Sum(i => i.Price * i.ThanhTien);
            hoaDonBan.TChiTietHdbs = Carts.Items.Select(i => new TChiTietHdb
            {
                Id = i.MaSp,
                SoLuongBan = i.SoLuong,
                DonGiaBan = i.Price
            }).ToList();
            // Tiếp tục cung cấp giá trị cho các trường còn thiếu...
            try
            {
                //Luu đơn hàng và chi tiết đơn hàng 
                _context.THoaDonBans.Add(hoaDonBan);
                await _context.SaveChangesAsync();
                HttpContext.Session.Remove("GioHang");
                return View("OrderCompleted", hoaDonBan.Id); // Trang xác nhận hoàn thành đơn hàng
            }
            catch (Exception ex)
            {
                // Xử lý nếu có lỗi khi lưu đơn hàng
                TempData["ErrorMessage"] = "Có lỗi xảy ra khi xử lý đơn hàng. Vui lòng thử lại sau.";
                // Điều hướng người dùng về trang chính hoặc trang thanh toán
                return RedirectToAction("Index");
            }
        }


        // Thêm action OrderComplete để hiển thị trang xác nhận hoàn thành đơn hàng
        private async Task<TDanhMucSp> GetTDanhMucSpFromDatabaseAsync(string Id)
        {
            // Trả về view "OrderCompleted" và truyền orderId vào làm mô hình dữ liệu
            return await _danhMucSpRepository.GetByIdAsync(Id);
        }



    }
}

DACSWebBanFlower/Views/Store/Index.cshtml
@model ShoppingCart
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        h2 {
            text-align: center;
            color: #343a40;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }

        th {
            background-color: #007bff;
            color: white;
        }

        .btn {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .btn-primary {
            background-color: #007bff;
            color: white;
        }

        .btn-danger {
            background-color: #dc3545;
            color: white;
        }

        .btn-success {
            background-color: #28a745;
            color: white;
        }

        .btn:hover {
            background-color: #0056b3;
        }

        .alert {
            margin-top: 20px;
            padding: 15px;
            border-radius: 5px;
            color: #0c5460;
            background-color: #d1ecf1;
            border: 1px solid #bee5eb;
        }

        .alert-heading {
            margin-top: 0;
        }

        .text-center {
            text-align: center;
        }

        img {
            max-width: 100%;
            height: auto;
        }
    </style>
    </head>
    <body>
    <div class="container mt-5">
        <h2 class="mb-4">Thông tin mua sắm</h2>

        @if (Model.Items.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Sản Phẩm</th>
                        <th scope="col">Giá</th>
                        <th scope="col">Số Lượng</th>
                        <th scope="col">Tổng giá</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>@item.TenSp</td>
                            <td>@item.Price</td>
                            <td>
                                <form asp-controller="Store" asp-action="UpdateCartItem" method="post">
                                    <input type="hidden" name="id" value="@item.MaSp" />
                                    <input type="number" name="SoLuong" id="SoLuong_@item.MaSp" value="@item.SoLuong" min="1" class="form-control" style="width: 80px;" />
                                    <button class="btn btn-primary btn-sm mt-2" type="submit">Update</button>
                                </form>
                            </td>

                            <td>@(item.Price * item.SoLuong)</td>
                            <td>
                                <form asp-action="RemoveFromCart" method="post">
                                    <input type="hidden" name="id" value="@item.MaSp" />
                                    <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                                </form>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

            <form asp-action="ClearAll" method="post">
                <button type="submit" class="btn btn-danger">Clear All</button>
            </form>


            <div class="text-center">
                <a class="btn btn-info btn-lg mr-3" asp-area="" asp-controller="Home" asp-action="Index">Tiếp tục mua sắm</a>
                <a class="btn btn-success btn-lg" asp-area="" asp-controller="Store" asp-action="ThanhToan">Thanh Toán</a>
            </div>
        }
        else
        {
            <div class="alert alert-info text-center" role="alert">
                <h4 class="alert-heading">Giỏ hàng của bạn đang trống.</h4>
                <hr>
                <p class="mb-0">Bạn chưa thêm bất kỳ sản phẩm nào vào giỏ hàng.</p>
                <button onclick="window.location.href='@Url.Action("Index", "Home")'" class="btn btn-primary mt-3">Bắt đầu mua sắm ngay!</button>
            </div>
        }

    </div>

    <div class="item active">
        <div class="col-sm-12">
            <h1 style="text-align: center;">Chào mừng đến với cửa hàng của chúng tôi!</h1>
            <img src="https://static.vecteezy.com/system/resources/previews/000/702/086/original/shopping-online-on-website-vector.jpg" width="100%" />
        </div>
    </div>
    </body>
</html>

DACSWebBanFlower/Views/Store/OrderCompleted.cshtml
@model string;
<h1>chúc mừng bạn đã thanh toán thành công</h1>
    <h2>mã mua đơn hàng của bạn là @Model</h2>

DACSWebBanFlower/Views/Store/ThanhToan.cshtml
@model THoaDonBan
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nhập thông tin đặt hàng</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center mb-4">Nhập thông tin đặt hàng</h1>
        <form asp-action="ThanhToan" method="post">
            <div class="form-group">
                <label asp-for="DiaChiDatHang">Địa chỉ giao hàng</label>
                <input asp-for="DiaChiDatHang" class="form-control" id="DiaChiDatHang">
            </div>
            <div class="form-group">
                <label asp-for="GhiChu">Ghi chú</label>
                <textarea asp-for="GhiChu" class="form-control" id="GhiChu"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Đặt hàng</button>
            <a class="btn btn-info btn-lg mr-2" asp-area="" asp-controller="Home" asp-action="Index">Trở về</a>
        </form>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>